# Generated by Django 6.0.5 on 2026-05-21 11:37

import cuhasc.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuhasc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='member_token',
            field=models.CharField(default=cuhasc.models.init_member_token, max_length=10),
        ),
    ]
