# Generated by Django 6.0.5 on 2026-06-25 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuhasc', '0004_qresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=20)),
            ],
        ),
    ]
