# Generated by Django 6.0.7 on 2026-08-01 10:20

import cuhasc.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuhasc', '0005_adminpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='order_seed',
            field=models.CharField(default=cuhasc.models.init_order_seed, max_length=8),
        ),
    ]
